menu:
- {name: 'research', url: '/research'}
- {name: 'teaching', url: '/teaching'}
- {name: 'cv', url: '/cv'}

social:
- {icon: 'github', link: 'https://github.com/martinneubrandt'}
- {icon: 'linkedin', link: 'www.linkedin.com/in/martinneubrandt'}